fastlane_version "2.5.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'RFLAN-QR-Scanner-2', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['me@timoliver.com.au', 'stevensmith.ome@gmail.com', 'the.damo@gmail.com', 'natashayelliott@gmail.com', 'themann@gmail.com', 'mitchellhancock97@gmail.com', 'trent@lloyd.id.au', 'megan.capp@gmail.com', 'elisha@spru.ce.id.au', 'sophie_webby_99@hotmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'e884c81af3347b33cc266813022c7f346077b04f',
             build_secret: '18e7ab5ba6fd8cc4c4f13d3cca445ff79a9ddff11e4d26dc7466db5726fba34b',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
